/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.tallerreparacioncelular.JFames;
import com.mycompany.tallerreparacioncelular.Controlador.TecnicoControlador;
import com.mycompany.tallerreparacioncelular.entidades.Tecnico;
import java.awt.BorderLayout;
import java.awt.GridLayout;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

public class TecnicoPanel extends javax.swing.JPanel {

    TecnicoControlador controlador = new TecnicoControlador();
    public TecnicoPanel() {
    initComponents();
    cargarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtNombresaa = new javax.swing.JLabel();
        txtApellidosaa = new javax.swing.JLabel();
        txtCedulaaa = new javax.swing.JLabel();
        txtCorreoaa = new javax.swing.JLabel();
        txtHabilidadesaa = new javax.swing.JLabel();
        txtDisponibilidadaa = new javax.swing.JLabel();
        txtCelularaa = new javax.swing.JLabel();
        txtHorasaa = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JButton();
        btnConsultar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTecnicos = new javax.swing.JTable();
        txtHoras = new javax.swing.JTextField();
        txtDisponibilidad = new javax.swing.JTextField();
        txtHabilidades = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        txtCedula = new javax.swing.JTextField();
        txtApellidos = new javax.swing.JTextField();
        txtNombres = new javax.swing.JTextField();
        txtCelular = new javax.swing.JTextField();

        jLabel1.setText("Técnico");

        txtNombresaa.setText("Nombres:");

        txtApellidosaa.setText("Apellidos:");

        txtCedulaaa.setText("Cédula:");

        txtCorreoaa.setText("Correo:");

        txtHabilidadesaa.setText("Habilidades:");

        txtDisponibilidadaa.setText("Disponibilidad:");

        txtCelularaa.setText("Celular:");

        txtHorasaa.setText("Horas trabajadas:");

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnConsultar.setText("Consultar");
        btnConsultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConsultarActionPerformed(evt);
            }
        });

        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        tblTecnicos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombres", "Apellidos", "Cédula", "Correo", "Habilidades", "Disponibilidad", "Celular", "Horas"
            }
        ));
        jScrollPane1.setViewportView(tblTecnicos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnRegistrar)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtHorasaa)
                                .addComponent(txtCelularaa)
                                .addComponent(txtDisponibilidadaa)
                                .addComponent(txtHabilidadesaa)
                                .addComponent(txtCorreoaa)
                                .addComponent(txtCedulaaa)
                                .addComponent(txtApellidosaa)
                                .addComponent(txtNombresaa)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btnConsultar)
                                .addGap(18, 18, 18)
                                .addComponent(btnActualizar)
                                .addGap(18, 18, 18)
                                .addComponent(btnEliminar)
                                .addGap(18, 18, 18)
                                .addComponent(btnLimpiar))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(txtApellidos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                                    .addComponent(txtCedula, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCorreo, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtHabilidades, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtHoras, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtDisponibilidad, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtCelular, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE))
                                    .addComponent(txtNombres, javax.swing.GroupLayout.Alignment.LEADING)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(319, 319, 319)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 788, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombresaa)
                    .addComponent(txtNombres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtApellidosaa)
                    .addComponent(txtApellidos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCedulaaa)
                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCorreoaa)
                    .addComponent(txtCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHabilidadesaa)
                    .addComponent(txtHabilidades, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtDisponibilidadaa)
                    .addComponent(txtDisponibilidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtCelularaa)
                    .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHorasaa)
                    .addComponent(txtHoras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrar)
                    .addComponent(btnConsultar)
                    .addComponent(btnActualizar)
                    .addComponent(btnEliminar)
                    .addComponent(btnLimpiar))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        try {
            Tecnico t = new Tecnico(
                txtNombres.getText(),
                txtApellidos.getText(),
                txtCedula.getText(),
                txtCorreo.getText(),
                txtHabilidades.getText(),
                txtDisponibilidad.getText(),
                txtCelular.getText(),
                Integer.parseInt(txtHoras.getText())
            );

            String mensaje = controlador.registrarTecnico(t);
            JOptionPane.showMessageDialog(this, mensaje);

            cargarTabla();
            limpiarCampos();

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "ERROR: HORAS TRABAJADAS DEBE SER UN NÚMERO.");
        }

    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        String cedula = txtCedula.getText();
        Tecnico t = controlador.consultarPorCedula(cedula);

        if (t == null) {
            JOptionPane.showMessageDialog(this, "ERROR: NO SE ENCONTRÓ TÉCNICO.");
            return;
        }

        txtNombres.setText(t.getNombres());
        txtApellidos.setText(t.getApellidos());
        txtCorreo.setText(t.getCorreo());
        txtHabilidades.setText(t.getHabilidades());
        txtDisponibilidad.setText(t.getDisponibilidad());
        txtCelular.setText(t.getCelular());
        txtHoras.setText(String.valueOf(t.getHorasTrabajadas()));

    }//GEN-LAST:event_btnConsultarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        String cedula = txtCedula.getText();

        String mensaje = controlador.eliminarTecnicoPorCedula(cedula);
        JOptionPane.showMessageDialog(this, mensaje);

        cargarTabla();
        limpiarCampos();

    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        try {
            Tecnico t = new Tecnico(
                txtNombres.getText(),
                txtApellidos.getText(),
                txtCedula.getText(),
                txtCorreo.getText(),
                txtHabilidades.getText(),
                txtDisponibilidad.getText(),
                txtCelular.getText(),
                Integer.parseInt(txtHoras.getText())
            );

            String mensaje = controlador.actualizarTecnico(t);
            JOptionPane.showMessageDialog(this, mensaje);

            cargarTabla();
            limpiarCampos();

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "ERROR: HORAS TRABAJADAS DEBE SER UN NÚMERO.");
        }

    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        limpiarCampos();
    }//GEN-LAST:event_btnLimpiarActionPerformed
    
    
    
    private void limpiarCampos() {
    txtNombres.setText("");
    txtApellidos.setText("");
    txtCedula.setText("");
    txtCorreo.setText("");
    txtHabilidades.setText("");
    txtDisponibilidad.setText("");
    txtCelular.setText("");
    txtHoras.setText("");
}
    
    private void cargarTabla() {
    DefaultTableModel modelo = (DefaultTableModel) tblTecnicos.getModel();
    modelo.setRowCount(0);

    for (Tecnico t : controlador.listarTecnicos()) {
        modelo.addRow(new Object[]{
            t.getId(),
            t.getNombres(),
            t.getApellidos(),
            t.getCedula(),
            t.getCorreo(),
            t.getHabilidades(),
            t.getDisponibilidad(),
            t.getCelular(),
            t.getHorasTrabajadas()
        });
        }
}
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnConsultar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTecnicos;
    private javax.swing.JTextField txtApellidos;
    private javax.swing.JLabel txtApellidosaa;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JLabel txtCedulaaa;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JLabel txtCelularaa;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JLabel txtCorreoaa;
    private javax.swing.JTextField txtDisponibilidad;
    private javax.swing.JLabel txtDisponibilidadaa;
    private javax.swing.JTextField txtHabilidades;
    private javax.swing.JLabel txtHabilidadesaa;
    private javax.swing.JTextField txtHoras;
    private javax.swing.JLabel txtHorasaa;
    private javax.swing.JTextField txtNombres;
    private javax.swing.JLabel txtNombresaa;
    // End of variables declaration//GEN-END:variables
}
